"""End-to-end self-iteration flow tests.

These tests answer the central question: when a realistic (faked, never truly
landed) change request is driven through the governed self-iteration workflow,
does the flow advance smoothly to the *single intended* human gate
(``waiting_owner_approval``) and then to ``done`` after approval — or does it
get stuck (``blocked`` / ``failed``) somewhere it should not?

Injection strategy
-------------------
The flow's "forward energy" is entirely the return value of
``agent_runner.run_agent``. We monkeypatch it (rather than a real LLM provider)
so that:
  * the Implementation Agent yields a *valid* ChangeSet, and
  * the Harness Agent yields a non-violation review.
That leaves the real ``workflow_tick`` state machine — the thing that actually
decides "advance vs block" — fully exercised. No real LLM, no real provider,
no real source mutation (edits target ``artifacts/drafts/`` in the temp repo).
"""

from __future__ import annotations

from typing import Any

import pytest

import abyss_cli.workflow as workflow
import abyss_cli.changeset as changeset
import abyss_cli.owner as owner


# --------------------------------------------------------------------------- #
# Fakes for the agent layer
# --------------------------------------------------------------------------- #

_VALID_CHANGESET_OPS = [
    {
        "id": "op_001",
        "kind": "fs.create_file",
        "target": {"path": "artifacts/drafts/e2e_demo_artifact.md"},
        "input": {"content": "# E2E demo artifact\n\nGenerated by a faked flow run.\n"},
    },
]


def _make_valid_changeset(changeset_id: str, roadmap_id: str) -> dict[str, Any]:
    return {
        "schema": "abyss.change_set.v1",
        "id": changeset_id,
        "roadmap_id": roadmap_id,
        "summary": "faked e2e change",
        "risk_level": "L2",
        "status": "proposed",
        "operations": _VALID_CHANGESET_OPS,
        "validation": {"ok": True, "messages": ["OK"]},
        "no_action_executed": True,
    }


def _install_happy_agents(monkeypatch: pytest.MonkeyPatch, *, roadmap_id: str) -> dict[str, list[str]]:
    """Patch run_agent + harness review to always succeed; record call order."""
    calls: dict[str, list[str]] = {"impl": [], "harness": []}

    def fake_run_agent(agent_id: str, target: str = "latest", provider: str | None = None):
        assert agent_id == "implementation"
        calls["impl"].append(target)
        cs_id = "chg_e2e_demo"
        record = _make_valid_changeset(cs_id, roadmap_id)
        # Persist it where the flow expects to load it from later.
        changeset.write_record(changeset._record_path(cs_id), record)
        result = dict(record)
        result["output_type"] = "changeset"
        agent_run = {"id": "agent_run_impl", "agent_id": "implementation"}
        return agent_run, result

    def fake_harness(target: str, provider: str | None = None):
        calls["harness"].append(target)
        agent_run = {"id": "agent_run_harness", "agent_id": "harness"}
        review = {
            "id": "hr_e2e_demo",
            "verdict": "within_executor_boundary",
            "recommendation": "owner_review",
        }
        return agent_run, review

    monkeypatch.setattr(workflow, "run_agent", fake_run_agent)
    monkeypatch.setattr(workflow, "run_harness_changeset_review", fake_harness)
    return calls


def _seed_workflow(roadmap_id: str = "R900") -> dict[str, Any]:
    """Create an approved-proposal-equivalent workflow directly.

    We bypass the evolution/LLM proposal-generation chain (which would itself
    call an LLM) and construct the workflow the way create_workflow_for_proposal
    would, since that part is not what this test is probing.
    """
    wf = {
        "schema": "abyss.workflow.v1",
        "id": workflow.new_id("wf"),
        "proposal_id": "evo_prop_fake_e2e",
        "roadmap_id": roadmap_id,
        "summary": "Add a small demo helper (faked e2e need)",
        "status": "implementation_pending",
        "provider": "cli",
        "source": "test_seed",
        "attempts": {"implementation": 0, "harness_review": 0, "execution": 0},
        "history": [
            {"at": workflow.now_iso(), "state": "implementation_pending", "event": "workflow_created"}
        ],
        "created_at": workflow.now_iso(),
        "updated_at": workflow.now_iso(),
    }
    workflow._write_workflow(wf)
    return wf


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #

def test_flow_advances_without_spurious_blocks_until_owner_gate(mini_repo, monkeypatch):
    """A healthy agent output should drive the flow straight to the owner gate.

    The ONLY stop before owner approval must be ``waiting_owner_approval``.
    No intermediate ``blocked`` / ``failed`` state is acceptable here.
    """
    wf = _seed_workflow()
    _install_happy_agents(monkeypatch, roadmap_id=str(wf["roadmap_id"]))

    results = workflow.workflow_run_until_wait(workflow_id=wf["id"], max_steps=12)

    statuses = [r.get("status") for r in results]
    # Final state is the intended human gate.
    final = workflow.load_workflow(wf["id"])
    assert final["status"] == "waiting_owner_approval", (
        f"flow did not reach owner gate; statuses seen: {statuses}; "
        f"last_error={final.get('last_error')}"
    )
    # And it never detoured into an unintended dead-end.
    history_states = [h.get("state") for h in final.get("history", [])]
    assert "blocked" not in history_states, f"unexpected block: {history_states}"
    assert "failed" not in history_states, f"unexpected failure: {history_states}"
    # An owner item must be waiting.
    assert final.get("owner_item_id")


def test_flow_completes_after_owner_approval(mini_repo, monkeypatch):
    """After the single human gate, the flow must reach ``done`` on its own."""
    wf = _seed_workflow()
    _install_happy_agents(monkeypatch, roadmap_id=str(wf["roadmap_id"]))

    # Avoid running the real integrity-check subprocess during the checking
    # stage; that is environment-dependent and not what we are probing here.
    monkeypatch.setattr(workflow, "run_checks", lambda: (True, ["stub integrity ok"]))

    workflow.workflow_run_until_wait(workflow_id=wf["id"], max_steps=12)
    gated = workflow.load_workflow(wf["id"])
    assert gated["status"] == "waiting_owner_approval"

    # Owner approves -> owner.approve_owner_item continues the workflow to done.
    item = owner.approve_owner_item(str(gated["owner_item_id"]), continue_workflow=True)
    assert item["status"] == "approved"

    final = workflow.load_workflow(wf["id"])
    assert final["status"] == "done", (
        f"flow did not complete after approval; "
        f"status={final['status']} last_error={final.get('last_error')}"
    )


def test_owner_gate_is_a_hard_stop_not_auto_passed(mini_repo, monkeypatch):
    """Without owner approval the flow must NOT self-advance past the gate.

    This confirms the human gate is a real gate (by design), distinguishing it
    from accidental stalls.
    """
    wf = _seed_workflow()
    _install_happy_agents(monkeypatch, roadmap_id=str(wf["roadmap_id"]))

    workflow.workflow_run_until_wait(workflow_id=wf["id"], max_steps=12)
    # Tick again many times WITHOUT approving.
    for _ in range(5):
        workflow.workflow_tick(workflow_id=wf["id"])

    final = workflow.load_workflow(wf["id"])
    assert final["status"] == "waiting_owner_approval"
    # It must not have executed anything.
    assert not final.get("execution_id")


def test_dry_run_failure_blocks_by_design(mini_repo, monkeypatch):
    """If the agent yields a changeset that fails dry-run, the flow blocks.

    This is a *designed* block, not a flow defect — we assert the flow surfaces
    it as ``blocked`` with a diagnostic, rather than silently stalling.
    """
    wf = _seed_workflow()

    def bad_run_agent(agent_id, target="latest", provider=None):
        cs_id = "chg_e2e_bad"
        # replace_exact against a file that does not exist -> dry-run/validate fails
        record = {
            "schema": "abyss.change_set.v1",
            "id": cs_id,
            "roadmap_id": str(wf["roadmap_id"]),
            "summary": "bad change",
            "risk_level": "L2",
            "status": "proposed",
            "operations": [
                {
                    "id": "op_bad",
                    "kind": "fs.replace_exact",
                    "target": {"path": "abyss_cli/does_not_exist.py"},
                    "input": {"old_content": "x", "new_content": "y"},
                }
            ],
            "validation": {"ok": True, "messages": ["OK"]},
        }
        changeset.write_record(changeset._record_path(cs_id), record)
        result = dict(record)
        result["output_type"] = "changeset"
        return {"id": "ar"}, result

    monkeypatch.setattr(workflow, "run_agent", bad_run_agent)

    workflow.workflow_run_until_wait(workflow_id=wf["id"], max_steps=12)
    final = workflow.load_workflow(wf["id"])
    assert final["status"] == "blocked"
    last = final["history"][-1]
    assert last["event"] == "dry_run_failed"
    assert last["details"].get("messages")
